[package]
name = "fedlogserver"
version = "0.1.0"
edition = "2021"


[dependencies]
actix = "0.13"
actix-web = "4"
actix-web-actors = "4.3"
mongodb = "2"
serde = "1"
serde_json = "1"
tokio = "1"
futures = "0.3"


[profile.release]
opt-level = "z"
lto = true
