[package]
name = "fedlogserver"
version = "0.1.0"
edition = "2021"


[dependencies]
actix = "0.12"
actix-web = "4.0.0-beta.14"
actix-web-actors = "4.0.0-beta.8"
lazy_static = "1"
mongodb = "2"
serde = "1"
serde_json = "1"
tokio = "1"
futures = "0.3"


[profile.release]
opt-level = "z"
lto = true
